from python:{{cookiecutter.python_version}}-alpine

maintainer "ymy1019@gmail.com"

run apk add --update alpine-sdk

# uwsgi
run apk add musl-dev linux-headers pcre-dev python-dev build-base

# mysqlclient
run apk add mariadb-dev
