version: "2"

services:
    rabbitmq:
        image: rabbitmq
        container_name: dev_rabbitmq
        expose:
            - 4369
            - 5671
            - 5672
            - 25672
        volumes:
            - ./var/rabbitmq_data:/var/lib/rabbitmq
    # see https://github.com/tomav/docker-mailserver
    mailserv:
        image: tvial/docker-mailserver:latest
        hostname: localhost
        domainname: localhost
        environment:
            MAIL_USER: "mail_sender"    # no account needed
            MAIL_PASS: "mail_passwd"
        expose:
            - 25
            - 143
            - 587
            - 993
        volumes:
            - ./var/mail_data/data:/var/mail
            - ./var/mail_data/config:/tmp/docker-mailserver/
    redis:
        image: redis:alpine
        container_name: dev_redis
        restart: always
        expose:
            - 6379
        volumes:
            - ./var/redis_data:/data
    memcached:
        image: memcached:alpine
        container_name: "dev_memcached"
        expose:
            - 11211
    mysql:
        image: mysql
        container_name: "dev_mysql"
        environment:
            MYSQL_ROOT_PASSWORD: "root_passwd"
            MYSQL_DATABASE: "{{ cookiecutter.project_name }}"
            MYSQL_USER: "{{ cookiecutter.project_name }}_user"
            MYSQL_PASSWORD: "{{ cookiecutter.project_name }}_passwd"
        expose:
            - 3306
    uwsgi:
        image: python:3.5.2-alpine
        container_name: "dev_uwsgi"
        env_file:
            - conf/staging.env
        expose:
            - 9527
        volumes:
            - ./:/sources
        links:
            - memcached
            - mysql
            - redis
    nginx:
        build: conf/nginx
        container_name: "dev_nginx"
        environment:
            SERVER_NAME: "localhost"
        ports:
            - "18080:80"
            - "18443:443"
        links:
            - uwsgi
